export class CharacterStats {
    BASE_HP: number;
    FIGHT_PROP_HP: number;
    FIGHT_PROP_HP_PERCENT: number;
    FIGHT_PROP_BASE_ATTACK: number;
    FIGHT_PROP_ATTACK: number;
    FIGHT_PROP_ATTACK_PERCENT: number;
    FIGHT_PROP_BASE_DEFENSE: number;
    FIGHT_PROP_DEFENSE: number;
    FIGHT_PROP_DEFENSE_PERCENT: number;
    FIGHT_PROP_BASE_SPEED: number;
    FIGHT_PROP_SPEED_PERCENT: number;
    FIGHT_PROP_HP_MP_PERCENT: number;
    FIGHT_PROP_ATTACK_MP_PERCENT: number;
    FIGHT_PROP_CRITICAL: number;
    FIGHT_PROP_ANTI_CRITICAL: number;
    FIGHT_PROP_CRITICAL_HURT: number;
    FIGHT_PROP_CHARGE_EFFICIENCY: number;
    FIGHT_PROP_ADD_HURT: number;
    FIGHT_PROP_SUB_HURT: number;
    FIGHT_PROP_HEAL_ADD: number;
    FIGHT_PROP_HEALED_ADD: number;
    FIGHT_PROP_ELEMENT_MASTERY: number;
    FIGHT_PROP_PHYSICAL_SUB_HURT: number;
    FIGHT_PROP_PHYSICAL_ADD_HURT: number;
    FIGHT_PROP_DEFENCE_IGNORE_RATIO: number;
    FIGHT_PROP_DEFENCE_IGNORE_DELTA: number;
    FIGHT_PROP_FIRE_ADD_HURT: number;
    FIGHT_PROP_ELEC_ADD_HURT: number;
    FIGHT_PROP_WATER_ADD_HURT: number;
    FIGHT_PROP_GRASS_ADD_HURT: number;
    FIGHT_PROP_WIND_ADD_HURT: number;
    FIGHT_PROP_ROCK_ADD_HURT: number;
    FIGHT_PROP_ICE_ADD_HURT: number;
    FIGHT_PROP_HIT_HEAD_ADD_HURT: number;
    FIGHT_PROP_FIRE_SUB_HURT: number;
    FIGHT_PROP_ELEC_SUB_HURT: number;
    FIGHT_PROP_WATER_SUB_HURT: number;
    FIGHT_PROP_GRASS_SUB_HURT: number;
    FIGHT_PROP_WIND_SUB_HURT: number;
    FIGHT_PROP_ROCK_SUB_HURT: number;
    FIGHT_PROP_ICE_SUB_HURT: number;
    FIGHT_PROP_EFFECT_HIT: number;
    FIGHT_PROP_EFFECT_RESIST: number;
    FIGHT_PROP_FREEZE_RESIST: number;
    FIGHT_PROP_TORPOR_RESIST: number;
    FIGHT_PROP_DIZZY_RESIST: number;
    FIGHT_PROP_FREEZE_SHORTEN: number;
    FIGHT_PROP_TORPOR_SHORTEN: number;
    FIGHT_PROP_DIZZY_SHORTEN: number;
    FIGHT_PROP_MAX_FIRE_ENERGY: number;
    FIGHT_PROP_MAX_ELEC_ENERGY: number;
    FIGHT_PROP_MAX_WATER_ENERGY: number;
    FIGHT_PROP_MAX_GRASS_ENERGY: number;
    FIGHT_PROP_MAX_WIND_ENERGY: number;
    FIGHT_PROP_MAX_ICE_ENERGY: number;
    FIGHT_PROP_MAX_ROCK_ENERGY: number;
    FIGHT_PROP_SKILL_CD_MINUS_RATIO: number;
    FIGHT_PROP_SHIELD_COST_MINUS_RATIO: number;
    FIGHT_PROP_CUR_FIRE_ENERGY: number;
    FIGHT_PROP_CUR_ELEC_ENERGY: number;
    FIGHT_PROP_CUR_WATER_ENERGY: number;
    FIGHT_PROP_CUR_GRASS_ENERGY: number;
    FIGHT_PROP_CUR_WIND_ENERGY: number;
    FIGHT_PROP_CUR_ICE_ENERGY: number;
    FIGHT_PROP_CUR_ROCK_ENERGY: number;
    FIGHT_PROP_CUR_HP: number;
    FIGHT_PROP_MAX_HP: number;
    FIGHT_PROP_CUR_ATTACK: number;
    FIGHT_PROP_CUR_DEFENSE: number;
    FIGHT_PROP_CUR_SPEED: number;
    FIGHT_PROP_NONEXTRA_ATTACK: number;
    FIGHT_PROP_NONEXTRA_DEFENSE: number;
    FIGHT_PROP_NONEXTRA_CRITICAL: number;
    FIGHT_PROP_NONEXTRA_CRITICAL_HURT: number;
    FIGHT_PROP_NONEXTRA_CHARGE_EFFICIENCY: number;
    FIGHT_PROP_NONEXTRA_ELEMENT_MASTERY: number;
    FIGHT_PROP_NONEXTRA_PHYSICAL_SUB_HURT: number;
    FIGHT_PROP_NONEXTRA_FIRE_ADD_HURT: number;
    FIGHT_PROP_NONEXTRA_ELEC_ADD_HURT: number;
    FIGHT_PROP_NONEXTRA_WATER_ADD_HURT: number;
    FIGHT_PROP_NONEXTRA_GRASS_ADD_HURT: number;
    FIGHT_PROP_NONEXTRA_WIND_ADD_HURT: number;
    FIGHT_PROP_NONEXTRA_ROCK_ADD_HURT: number;
    FIGHT_PROP_NONEXTRA_ICE_ADD_HURT: number;
    FIGHT_PROP_NONEXTRA_FIRE_SUB_HURT: number;
    FIGHT_PROP_NONEXTRA_ELEC_SUB_HURT: number;
    FIGHT_PROP_NONEXTRA_WATER_SUB_HURT: number;
    FIGHT_PROP_NONEXTRA_GRASS_SUB_HURT: number;
    FIGHT_PROP_NONEXTRA_WIND_SUB_HURT: number;
    FIGHT_PROP_NONEXTRA_ROCK_SUB_HURT: number;
    FIGHT_PROP_NONEXTRA_ICE_SUB_HURT: number;
    FIGHT_PROP_NONEXTRA_SKILL_CD_MINUS_RATIO: number;
    FIGHT_PROP_NONEXTRA_SHIELD_COST_MINUS_RATIO: number;
    FIGHT_PROP_NONEXTRA_PHYSICAL_ADD_HURT: number;
    constructor(stats: Record<string, number>) {
        this.BASE_HP = stats["1"] || 0;
        this.FIGHT_PROP_HP = stats["2"] || 0;
        this.FIGHT_PROP_HP_PERCENT = stats["3"] || 0;
        this.FIGHT_PROP_BASE_ATTACK = stats["4"] || 0;
        this.FIGHT_PROP_ATTACK = stats["5"] || 0;
        this.FIGHT_PROP_ATTACK_PERCENT = stats["6"] || 0;
        this.FIGHT_PROP_BASE_DEFENSE = stats["7"] || 0;
        this.FIGHT_PROP_DEFENSE = stats["8"] || 0;
        this.FIGHT_PROP_DEFENSE_PERCENT = stats["9"] || 0;
        this.FIGHT_PROP_BASE_SPEED = stats["10"] || 0;
        this.FIGHT_PROP_SPEED_PERCENT = stats["11"] || 0;
        this.FIGHT_PROP_HP_MP_PERCENT = stats["12"] || 0;
        this.FIGHT_PROP_ATTACK_MP_PERCENT = stats["13"] || 0;
        this.FIGHT_PROP_CRITICAL = stats["20"] || 0;
        this.FIGHT_PROP_ANTI_CRITICAL = stats["21"] || 0;
        this.FIGHT_PROP_CRITICAL_HURT = stats["22"] || 0;
        this.FIGHT_PROP_CHARGE_EFFICIENCY = stats["23"] || 0;
        this.FIGHT_PROP_ADD_HURT = stats["24"] || 0;
        this.FIGHT_PROP_SUB_HURT = stats["25"] || 0;
        this.FIGHT_PROP_HEAL_ADD = stats["26"] || 0;
        this.FIGHT_PROP_HEALED_ADD = stats["27"] || 0;
        this.FIGHT_PROP_ELEMENT_MASTERY = stats["28"] || 0;
        this.FIGHT_PROP_PHYSICAL_SUB_HURT = stats["29"] || 0;
        this.FIGHT_PROP_PHYSICAL_ADD_HURT = stats["30"] || 0;
        this.FIGHT_PROP_DEFENCE_IGNORE_RATIO = stats["31"] || 0;
        this.FIGHT_PROP_DEFENCE_IGNORE_DELTA = stats["32"] || 0;
        this.FIGHT_PROP_FIRE_ADD_HURT = stats["40"] || 0;
        this.FIGHT_PROP_ELEC_ADD_HURT = stats["41"] || 0;
        this.FIGHT_PROP_WATER_ADD_HURT = stats["42"] || 0;
        this.FIGHT_PROP_GRASS_ADD_HURT = stats["43"] || 0;
        this.FIGHT_PROP_WIND_ADD_HURT = stats["44"] || 0;
        this.FIGHT_PROP_ROCK_ADD_HURT = stats["45"] || 0;
        this.FIGHT_PROP_ICE_ADD_HURT = stats["46"] || 0;
        this.FIGHT_PROP_HIT_HEAD_ADD_HURT = stats["47"] || 0;
        this.FIGHT_PROP_FIRE_SUB_HURT = stats["50"] || 0;
        this.FIGHT_PROP_ELEC_SUB_HURT = stats["51"] || 0;
        this.FIGHT_PROP_WATER_SUB_HURT = stats["52"] || 0;
        this.FIGHT_PROP_GRASS_SUB_HURT = stats["53"] || 0;
        this.FIGHT_PROP_WIND_SUB_HURT = stats["54"] || 0;
        this.FIGHT_PROP_ROCK_SUB_HURT = stats["55"] || 0;
        this.FIGHT_PROP_ICE_SUB_HURT = stats["56"] || 0;
        this.FIGHT_PROP_EFFECT_HIT = stats["60"] || 0;
        this.FIGHT_PROP_EFFECT_RESIST = stats["61"] || 0;
        this.FIGHT_PROP_FREEZE_RESIST = stats["32"] || 0;
        this.FIGHT_PROP_TORPOR_RESIST = stats["63"] || 0;
        this.FIGHT_PROP_DIZZY_RESIST = stats["64"] || 0;
        this.FIGHT_PROP_FREEZE_SHORTEN = stats["65"] || 0;
        this.FIGHT_PROP_TORPOR_SHORTEN = stats["66"] || 0;
        this.FIGHT_PROP_DIZZY_SHORTEN = stats["67"] || 0;
        this.FIGHT_PROP_MAX_FIRE_ENERGY = stats["70"] || 0;
        this.FIGHT_PROP_MAX_ELEC_ENERGY = stats["71"] || 0;
        this.FIGHT_PROP_MAX_WATER_ENERGY = stats["72"] || 0;
        this.FIGHT_PROP_MAX_GRASS_ENERGY = stats["73"] || 0;
        this.FIGHT_PROP_MAX_WIND_ENERGY = stats["74"] || 0;
        this.FIGHT_PROP_MAX_ICE_ENERGY = stats["75"] || 0;
        this.FIGHT_PROP_MAX_ROCK_ENERGY = stats["76"] || 0;
        this.FIGHT_PROP_SKILL_CD_MINUS_RATIO = stats["80"] || 0;
        this.FIGHT_PROP_SHIELD_COST_MINUS_RATIO = stats["81"] || 0;

        this.FIGHT_PROP_CUR_FIRE_ENERGY = stats["1000"] || 0;
        this.FIGHT_PROP_CUR_ELEC_ENERGY = stats["1001"] || 0;
        this.FIGHT_PROP_CUR_WATER_ENERGY = stats["1002"] || 0;
        this.FIGHT_PROP_CUR_GRASS_ENERGY = stats["1003"] || 0;
        this.FIGHT_PROP_CUR_WIND_ENERGY = stats["1004"] || 0;
        this.FIGHT_PROP_CUR_ICE_ENERGY = stats["1005"] || 0;
        this.FIGHT_PROP_CUR_ROCK_ENERGY = stats["1006"] || 0;
        this.FIGHT_PROP_CUR_HP = stats["1010"] || 0;

        this.FIGHT_PROP_MAX_HP = stats["2000"] || 0;
        this.FIGHT_PROP_CUR_ATTACK = stats["2001"] || 0;
        this.FIGHT_PROP_CUR_DEFENSE = stats["2002"] || 0;
        this.FIGHT_PROP_CUR_SPEED = stats["2003"] || 0;

        this.FIGHT_PROP_NONEXTRA_ATTACK = stats["3000"] || 0;
        this.FIGHT_PROP_NONEXTRA_DEFENSE = stats["3001"] || 0;
        this.FIGHT_PROP_NONEXTRA_CRITICAL = stats["3002"] || 0;
        this.FIGHT_PROP_CUR_SPEED = stats["3003"] || 0;
        this.FIGHT_PROP_NONEXTRA_CRITICAL_HURT = stats["3004"] || 0;
        this.FIGHT_PROP_NONEXTRA_CHARGE_EFFICIENCY = stats["3005"] || 0;
        this.FIGHT_PROP_NONEXTRA_ELEMENT_MASTERY = stats["3006"] || 0;
        this.FIGHT_PROP_NONEXTRA_PHYSICAL_SUB_HURT = stats["3007"] || 0;
        this.FIGHT_PROP_NONEXTRA_FIRE_ADD_HURT = stats["3008"] || 0;
        this.FIGHT_PROP_NONEXTRA_ELEC_ADD_HURT = stats["3009"] || 0;
        this.FIGHT_PROP_NONEXTRA_WATER_ADD_HURT = stats["3010"] || 0;
        this.FIGHT_PROP_NONEXTRA_GRASS_ADD_HURT = stats["3011"] || 0;
        this.FIGHT_PROP_NONEXTRA_WIND_ADD_HURT = stats["3012"] || 0;
        this.FIGHT_PROP_NONEXTRA_ROCK_ADD_HURT = stats["3013"] || 0;
        this.FIGHT_PROP_NONEXTRA_ICE_ADD_HURT = stats["3014"] || 0;
        this.FIGHT_PROP_NONEXTRA_FIRE_SUB_HURT = stats["3015"] || 0;
        this.FIGHT_PROP_NONEXTRA_ELEC_SUB_HURT = stats["3016"] || 0;
        this.FIGHT_PROP_NONEXTRA_WATER_SUB_HURT = stats["3017"] || 0;
        this.FIGHT_PROP_NONEXTRA_GRASS_SUB_HURT = stats["3018"] || 0;
        this.FIGHT_PROP_NONEXTRA_WIND_SUB_HURT = stats["3019"] || 0;
        this.FIGHT_PROP_NONEXTRA_ROCK_SUB_HURT = stats["3020"] || 0;
        this.FIGHT_PROP_NONEXTRA_ICE_SUB_HURT = stats["3021"] || 0;
        this.FIGHT_PROP_NONEXTRA_SKILL_CD_MINUS_RATIO = stats["3022"] || 0;
        this.FIGHT_PROP_NONEXTRA_SHIELD_COST_MINUS_RATIO = stats["3023"] || 0;
        this.FIGHT_PROP_NONEXTRA_PHYSICAL_ADD_HURT = stats["3024"] || 0;
    }
}
